[package]
name = "net"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
snafu = "0.8.5"
tokio = { version = "1.44.2", features = ["io-util", "net", "time"] }
uuid = { version = "1.16.0", features = ["v4"] }
